name: CI for MERN Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: ✅ Run backend tests
        working-directory: ./server
        run: npm test

      - name: 📦 Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: ✅ Run frontend tests
        working-directory: ./client
        run: npm test
